[metadata]
name = pminflux-sim
version = 2.0.0
description = Simulador y estimador p-MINFLUX pulsado con fuga entre ventanas (v2)
long_description = file: README.md
long_description_content_type = text/markdown

[options]
package_dir =
    = src
packages = find:
python_requires = >=3.8
install_requires =
    numpy
    scipy

[options.packages.find]
where = src

[options.extras_require]
figs = matplotlib
